-- Find total customers by countries
select
country,
count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers DESC

-- Find total customers by gender
select
gender,
count(gender) as total_customers
from gold.dim_customers
group by gender
order by total_customers DESC

-- Find total products by category
select
category,
count(product_key) as total_product
from gold.dim_products
group by category
order by total_product DESC

-- What is the average costs in each category?
select
category,
avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost DESC

-- What is the total revenue generated by each category?
select
p.category,
sum(s.sales_amount) total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key = p.product_key
group by p.category
order by total_revenue DESC

-- Find total revenue generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
Order by total_revenue DESC

-- What is the distribution of sold items across countries
select
c.country,
sum(s.quantity) as total_sold_items
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by 
c.country
Order by total_sold_items DESC

